format = """
[](#240046)\
$os\
$username\
[](bg:#3c096c fg:#240046)\
$directory\
[](fg:#3c096c bg:#5a189a)\
$git_branch\
$git_status\
[](fg:#5a189a bg:#7b2cbf)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#7b2cbf bg:#9D4EDD)\
$time\
[](fg:#9D4EDD)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#240046"
style_root = "bg:#240046"
# format = '[$user ]($style)'
format = '[  ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#240046"
disabled = true # Disabled by default

[directory]
style = "bg:#3c096c"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#7b2cbf"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#9D4EDD"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#7b2cbf"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#7b2cbf"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#5a189a"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#5a189a"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#7b2cbf"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#7b2cbf"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#7b2cbf"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#7b2cbf"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#7b2cbf"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#7b2cbf"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#7b2cbf"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#7b2cbf"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#7b2cbf"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#9D4EDD"
format = '[   $time ]($style)'